[cursor]
blink_interval = 450
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 17

[font.bold]
family = "Inconsolata-dz for Powerline"

[font.bold_italic]
family = "monospace"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "monospace"

[font.normal]
family = "FiraCode Nerd Font"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Control"

[scrolling]
multiplier = 3

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true
