#+TITLE: Doom Emacs config
#+AUTHOR: Nazih Boudaakkar
#+EMAIL: nazih.boudaakkar@proton.me
#+DESCRIPTION: My doom emacs config in org mode using literate programming

* Table Of Content :toc:
- [[#peronal-meta-data][Peronal Meta data]]
- [[#display][Display]]
  - [[#font][Font]]
  - [[#theme][Theme]]
  - [[#vertico][Vertico]]
  - [[#tabs][Tabs]]
  - [[#neo-tree][Neo-tree]]
- [[#keymaps][Keymaps]]
  - [[#dired][Dired]]
- [[#plugins][Plugins]]
  - [[#org-mode][Org mode]]
  - [[#tree-sitter][Tree-sitter]]
  - [[#python-pyright][Python Pyright]]
  - [[#python-venv-auto-activate][Python Venv auto activate]]
  - [[#company-mode][Company mode]]
  - [[#codeium][Codeium]]
- [[#debugging][Debugging]]
  - [[#dap-ui][DAP-UI]]

* Peronal Meta data
;; Place your private configuration here! Remember, you do not need to run 'doom
;; sync' after modifying this file!


;; If you use `org' and don't want your org files in the default location below,
;; change `org-directory'. It must be set before org loads!



#+begin_src elisp
;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets. It is optional.
(setq user-full-name "Nazih Boudaakkar"
      user-mail-address "nazih.boudaakkar@proton.me")

#+end_src

* Display
** Font
;; Doom exposes five (optional) variables for controlling fonts in Doom:
;;
;; - `doom-font' -- the primary font to use
;; - `doom-variable-pitch-font' -- a non-monospace font (where applicable)
;; - `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;; - `doom-symbol-font' -- for symbols
;; - `doom-serif-font' -- for the `fixed-pitch-serif' face
;;
;; See 'C-h v doom-font' for documentation and more examples of what they
;; accept. For example:
;;
;;(setq doom-font (font-spec :family "Fira Code" :size 12 :weight 'semi-light)
;;      doom-variable-pitch-font (font-spec :family "Fira Sans" :size 13))


#+begin_src elisp
(setq doom-font                 (font-spec :family "FiraCode Nerd Font" :size 17)
      doom-big-font             (font-spec :family "FiraCode Nerd Font" :size 23)
      doom-variable-pitch-font  (font-spec :family "SauceCodePro Nerd Font" :size 20)
      doom-serif-font           (font-spec :family "Liberation Serif" :size 17))

(after! doom-themes
        (setq   doom-themes-enable-bold t
                doom-themes-enable-italic t))
(custom-set-faces!
  '(font-lock-comment-face :slant italic)
  '(font-lock-keyword-face :slant italic))
#+end_src

** Theme
;; If you or Emacs can't find your font, use 'M-x describe-font' to look the
;; up, `M-x eval-region' to execute elisp code, and 'M-x doom/reload-font' to
;; refresh your font settings. If Emacs still can't find your font, it likely
;; wasn't installed correctly. Font issues are rarely Doom issues!

;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:
#+begin_src elisp
(setq doom-theme 'doom-tokyo-night)

;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
(setq display-line-numbers-type 'relative)

#+end_src

;; Whenever you reconfigure a package, make sure to wrap your config in an
;; `after!' block, otherwise Doom's defaults may override your settings. E.g.
;;
;;   (after! PACKAGE
;;     (setq x y))
;;
;; The exceptions to this rule:
;;
;;   - Setting file/directory variables (like `org-directory')
;;   - Setting variables which explicitly tell you to set them before their
;;     package is loaded (see 'C-h v VARIABLE' to look up their documentation).
;;   - Setting doom variables (which start with 'doom-' or '+').
;;
;; Here are some additional functions/macros that will help you configure Doom.
;;
;; - `load!' for loading external *.el files relative to this one

;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;; Alternatively, use `C-h o' to look up a symbol (functions, variables, faces,
;; etc).
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.
** Vertico

#+begin_src elisp

(require 'vertico-posframe)
(vertico-posframe-mode 1)

(setq vertico-posframe-parameters
     '((left-fringe . 8)
       (right-fringe . 8)))
#+end_src
** Tabs
#+begin_src emacs-lisp

(setq-default tab-width 4)

#+end_src

** Neo-tree
#+begin_src elisp

(setq neo-theme (if (display-graphic-p) 'arrow))

#+end_src

* Keymaps
** Dired
*** Add file
#+begin_src emacs-lisp
(after! dired
  (map! :map dired-mode-map
        :leader "f n" #'dired-create-empty-file))
#+end_src

* Plugins
** Org mode
*** CSS
#+begin_src elisp

;; Don't forget to add the following header at the top of the org file
;; #+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://gongzhitaao.org/orgcss/org.css"/>
(setq org-html-htmlize-output-type 'css)

#+end_src
*** Org templates
#+begin_src emacs-lisp
(after! org
  ;; Personal tasks
  (setq org-capture-templates
        '(("p" "Personal TODO" entry
           (file+headline "~/Dropbox/org/personal.org" "Tasks")
           "* TODO %?\nSCHEDULED: %^t\nDEADLINE: %^t\n%a\n")
          ("P" "Personal TODO with Category" entry
           (file+headline "~/Dropbox/org/personal.org" "Tasks")
           "* TODO %?\nSCHEDULED: %^t\nDEADLINE: %^t\n%a\n%i\nCategory: %^{Category}\n")))

  ;; Freelance tasks
  (setq org-capture-templates
        (append org-capture-templates
                '(("f" "Freelance TODO" entry
                   (file+headline "~/Dropbox/org/freelance.org" "Tasks")
                   "* TODO %?\nSCHEDULED: %^t\nDEADLINE: %^t\n%a\n")
                  ("F" "Freelance TODO with Project" entry
                   (file+headline "~/Dropbox/org/freelance.org" "Tasks")
                   "* TODO %?\nSCHEDULED: %^t\nDEADLINE: %^t\n%a\n%i\nProject: %^{Project}\n")))))

(setq org-agenda-files '("~/Dropbox/org/personal.org" "~/Dropbox/org/freelance.org"))
#+end_src
*** Dropbox Sync
#+begin_src emacs-lisp
(setq org-directory "~/Dropbox/org/")
#+end_src

** Tree-sitter
#+begin_src emacs-lisp
(setq treesit-language-source-alist
   '((bash "https://github.com/tree-sitter/tree-sitter-bash")
     (cmake "https://github.com/uyha/tree-sitter-cmake")
     (css "https://github.com/tree-sitter/tree-sitter-css")
     (elisp "https://github.com/Wilfred/tree-sitter-elisp")
     (go "https://github.com/tree-sitter/tree-sitter-go")
     (html "https://github.com/tree-sitter/tree-sitter-html")
     (javascript "https://github.com/tree-sitter/tree-sitter-javascript" "master" "src")
     (json "https://github.com/tree-sitter/tree-sitter-json")
     (make "https://github.com/alemuller/tree-sitter-make")
     (markdown "https://github.com/ikatyang/tree-sitter-markdown")
     (python "https://github.com/tree-sitter/tree-sitter-python")
     (toml "https://github.com/tree-sitter/tree-sitter-toml")
     (tsx "https://github.com/tree-sitter/tree-sitter-typescript" "master" "tsx/src")
     (typescript "https://github.com/tree-sitter/tree-sitter-typescript" "master" "typescript/src")
     (yaml "https://github.com/ikatyang/tree-sitter-yaml")))

(use-package treesit-auto
        :demand t
        :config
        (global-treesit-auto-mode)
  )

#+end_src
** Python Pyright
#+begin_src elisp

;(use-package lsp-pyright
;  :hook (python-mode . (lambda ()
;                          (require 'lsp-pyright)
;                          (lsp))))  ; or lsp-deferred

#+end_src

** Python Venv auto activate
#+begin_src elisp

(use-package pyvenv
  :config
  (pyvenv-mode t)

  ;; Set correct Python interpreter
  (setq pyvenv-post-activate-hooks
        (list (lambda ()
                (setq python-shell-interpreter (concat pyvenv-virtual-env "bin/python3")))))
  (setq pyvenv-post-deactivate-hooks
        (list (lambda ()
                (setq python-shell-interpreter "python3")))))

#+end_src
** Company mode
#+begin_src emacs-lisp

;; we recommend using use-package to organize your init.el
;; (use-package codeium
;;     ;; if you use straight
;;     ;; :straight '(:type git :host github :repo "Exafunction/codeium.el")
;;     ;; otherwise, make sure that the codeium.el file is on load-path

;;     :init
;;     ;; use globally
;;     (add-to-list 'completion-at-point-functions #'codeium-completion-at-point)
;;     ;; or on a hook
;;     ;; (add-hook 'python-mode-hook
;;     ;;     (lambda ()
;;     ;;         (setq-local completion-at-point-functions '(codeium-completion-at-point))))

;;     ;; if you want multiple completion backends, use cape (https://github.com/minad/cape):
;;     ;; (add-hook 'python-mode-hook
;;     ;;     (lambda ()
;;     ;;         (setq-local completion-at-point-functions
;;     ;;             (list (cape-super-capf #'codeium-completion-at-point #'lsp-completion-at-point)))))
;;     ;; an async company-backend is coming soon!

;;     ;; codeium-completion-at-point is autoloaded, but you can
;;     ;; optionally set a timer, which might speed up things as the
;;     ;; codeium local language server takes ~0.2s to start up
;;     (add-hook 'emacs-startup-hook
;;      (lambda () (run-with-timer 0.1 nil #'codeium-init)))

;;     :defer t ;; lazy loading, if you want
;;     :config
;;     ;; (setq use-dialog-box nil) ;; do not use popup boxes

;;     ;; if you don't want to use customize to save the api-key
;;     ;; (setq codeium/metadata/api_key "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx")

;;     ;; get codeium status in the modeline
;;     (setq codeium-mode-line-enable
;;         (lambda (api) (not (memq api '(CancelRequest Heartbeat AcceptCompletion)))))
;;     (add-to-list 'mode-line-format '(:eval (car-safe codeium-mode-line)) t)
;;     ;; alternatively for a more extensive mode-line
;;     ;; (add-to-list 'mode-line-format '(-50 "" codeium-mode-line) t)

;;     ;; use M-x codeium-diagnose to see apis/fields that would be sent to the local language server
;;     (setq codeium-api-enabled
;;         (lambda (api)
;;             (memq api '(GetCompletions Heartbeat CancelRequest GetAuthToken RegisterUser auth-redirect AcceptCompletion))))
;;     ;; you can also set a config for a single buffer like this:
;;     ;; (add-hook 'python-mode-hook
;;     ;;     (lambda ()
;;     ;;         (setq-local codeium/editor_options/tab_size 4)))

;;     ;; You can overwrite all the codeium configs!
;;     ;; for example, we recommend limiting the string sent to codeium for better performance
;;     (defun my-codeium/document/text ()
;;         (buffer-substring-no-properties (max (- (point) 3000) (point-min)) (min (+ (point) 1000) (point-max))))
;;     ;; if you change the text, you should also change the cursor_offset
;;     ;; warning: this is measured by UTF-8 encoded bytes
;;     (defun my-codeium/document/cursor_offset ()
;;         (codeium-utf8-byte-length
;;             (buffer-substring-no-properties (max (- (point) 3000) (point-min)) (point))))
;;     (setq codeium/document/text 'my-codeium/document/text)
;;     (setq codeium/document/cursor_offset 'my-codeium/document/cursor_offset))


#+end_src
** Codeium
#+begin_src elisp

;; (use-package company
;;     :defer 0.1
;;     :config
;;     (global-company-mode t)
;;     (setq-default
;;         company-idle-delay 0.05
;;         company-require-match nil
;;         company-minimum-prefix-length 0

;;         ;; get only preview
;;         ;; company-frontends '(company-preview-frontend)
;;         ;; also get a drop down
;;         company-frontends '(company-pseudo-tooltip-frontend company-preview-frontend)
;;         ))

#+end_src
* Debugging
** DAP-UI
#+begin_src emacs-lisp
;; (setq dap-auto-configure-features '(sessions locals controls tooltip))
#+end_src
*** Python
#+begin_src emacs-lisp
;; (require 'dap-python)
;; if you installed debugpy, you need to set this
;; https://github.com/emacs-lsp/dap-mode/issues/306
;; (setq dap-python-debugger 'debugpy)
#+end_src
